### ISSUE TITLE
Combine registration of schema with registration of metadata to have tighter constraints and simplify indexer logic

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1043]
pulled out from #760
> Can we tighten constraints around schema + metadata? i.e. always register key schema + value schema + metadata together (like a regular table), so we can reliably expect them to exist together, and not allow for them to be written more than once. -> yes

**Comment by holic** [comment]
We chatted earlier, just summarizing here.

Since this change is tightly coupled to things like store-cache, current and future networking code, etc., we decided to punt for a little while longer until the new networking code is complete (leaning on some workarounds for lack of key name, that should hopefully clear up with #1025 and an expanded config).

In the meantime, do we wanna add key names via #1059?
