### ISSUE TITLE
SyncWorker failing with error

### ISSUE THREAD

**Issue by Kooshaba** [latticexyz/mud#1091]
<img width="1006" alt="CleanShot 2023-06-29 at 15 40 45@2x" src="https://github.com/latticexyz/mud/assets/4297920/bc35cf0a-4891-453d-8ab0-b1c0c364432f">

Something is getting passed to `postMessage` that is not serializable by a web worker.

**Comment by Kooshaba** [comment]
I'm looking into this further as Sky Strife desperately needs the SyncWorker to handle the amount of state we are dealing with in the match structure.

**Comment by Kooshaba** [comment]
@holic I found what it is. `devEmit` was added as part of the event coming from the worker, but the function can't be serialized into JSON. As a quick fix I'm down to disable `devEmit` and break dev tools because we mainly need this for production deployments.

**Comment by holic** [comment]
Sounds good! Thanks for digging!On Jun 29, 2023, at 9:12 PM, Andy Cernera ***@***.***> wrote:﻿
@holic I found what it is. devEmit was added as part of the event coming from the worker, but the function can't be serialized into JSON. As a quick fix I'm down to disable devEmit and break dev tools because we mainly need this for production deployments.

**Comment by Kooshaba** [comment]
#1109 PR opened here

**Comment by alvrs** [comment]
PR got merged (and SyncWorker is deprecated now)
