### ISSUE TITLE
Consider adding resource type to resource selector

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1394]
Right now we generally use the pattern:
```
namespace (bytes16) + name (bytes16)
```

I am proposing we explore a pattern like:
```
resource type (bytes2) + namespace (bytes14) + name (bytes16)
```

This comes from seeing a few patterns emerge:
- `ResourceType` table/enum for registering systems: https://github.com/latticexyz/mud/blob/5150544354816949ab3d47950df7fc67ded797a7/packages/world/mud.config.ts#L95-L102
- module namespace suffix: https://github.com/latticexyz/mud/blob/5150544354816949ab3d47950df7fc67ded797a7/packages/world/src/modules/uniqueentity/constants.sol#L5
- onchain table vs offchain tables: https://github.com/latticexyz/mud/pull/1496#discussion_r1326925880

**Comment by alvrs** [comment]
A semi-related thing to consider here is that we currently don't write to the `ResourceType` table if the table is registered directly via `StoreCore` instead of a call to `world.registerTable` (because `ResourceType` is a `World` concept, not a `Store` concept). Encoding the resource type in the selector might solve this if it means we don't need `ResourceType` anymore.
