### ISSUE TITLE
postgres indexer: uint16 doesn't fit into postgres smallint column type

### ISSUE THREAD

**Issue by rohanabraham** [latticexyz/mud#2077]
One other issue with the Indexer, as I was trying it on Redstone; it worked very well until an issue was last_updated_block_number 1539672

PostgresError: value "32896" is out of range for type smallint
    at ErrorResponse (file:///xxxxx/.npm/_npx/fd18aa7d46b32af0/node_modules/postgres/src/connection.js:790:26)
    at handle (file:///xxxxx/.npm/_npx/fd18aa7d46b32af0/node_modules/postgres/src/connection.js:476:6)
    at Socket.data (file:///xxxxx/.npm/_npx/fd18aa7d46b32af0/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:515:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '22003',
  where: "unnamed portal parameter $1 = '...'",
  file: 'numutils.c',
  line: '349',
  routine: 'pg_strtoint16_safe'

Was running npx -y -p @latticexyz/store-indexer@next postgres-indexer

**Comment by holic** [comment]
Are you indexing all worlds or just your own world? Do you have MUD's debug logs turned on? Curious to know where the source of this data is coming from.

**Comment by holic** [comment]
https://github.com/latticexyz/mud/blob/a60c13916c043d010686a9bd4979b6aaa3cd46df/packages/store-sync/src/postgres-decoded/buildColumn.ts#L12-L17

Our `buildColumn` method attempts to use `smallint` (equivalent to signed `int2`) for `uint16`, but overflows because `uint16` can exceed the max value of a 2-byte signed integer.

```
➜ type(int16).max
Type: int16
├ Hex: 0x7fff
├ Hex (full word): 0x0000000000000000000000000000000000000000000000000000000000007fff
└ Decimal: 32767
➜ type(uint16).max
Type: uint16
├ Hex: 0xffff
├ Hex (full word): 0x000000000000000000000000000000000000000000000000000000000000ffff
└ Decimal: 65535
```

Need to either bump up the column type or somehow specify whether the column is signed/unsigned (unclear of pg allows this).

I also found this in the pg docs:
> The type integer is the common choice, as it offers the best balance between range, storage size, and performance. The smallint type is generally only used if disk space is at a premium. The bigint type is designed to be used when the range of the integer type is insufficient.

We could potentially switch everything to `numeric` but unclear what the trade-offs are in terms of performance.

**Comment by holic** [comment]
IIRC Ryan suggested that if we don't need to save on storage that it might be fine to skip `smallint` and maybe even `integer`, just to reduce the number of different types floating around and having to cast between em
