### ISSUE TITLE
deploy should emit system ID<>ABI mapping

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2349]
to make it easier to use direct system calls (`world.call`) across platforms (not dependent on our TS config)

> either way we should probably output some language/platform agnostic deploy artifacts that map system solidity files to their system IDs
> so its easier to do these calls/mappings

**Comment by 0xxlegolas** [comment]
Currently, the ABI generated json files has namespaced_functionNames. If we are using direct calls from the clients(non TS) its totally fine, But if we are using either call or callFrom in the clients 

1. We need a abi (without namespace) and the systemId information about the function 

It would be great to have this abi information and systemId information for non typescript clients in one place

**Comment by holic** [comment]
we're now registering all system and world function signatures: https://github.com/latticexyz/mud/issues/2382

this should let you generate an ABI given a system ID - is this enough?

**Comment by qbzzt** [comment]
IMAO, no. An ABI also needs to include the return values.

**Comment by 0xxlegolas** [comment]
> registering all system and world function signatures

@holic Is this abi generated without namespace ? Also how is this generated, can you give more info. 

Moreover, giving the system id and generating abi looks like a heavy lifting in the client. 
- Client should know what system does the function live 
- Client should know what namespace does the system live 

**End Goal:** 
Ideally, it would be great if the client is agnostic of whats happening in the smart contract layer except for encoding the functions using abi. 
- Is it possible to use `callFrom` with namespaced functions instead of systemId. So that the abi is generated with the namespace and it can be used by the clients no matter what call it makes. eg: `callFrom(delegator, calldata)`

What we have now as temporary solution to use call or callFrom from our clients:
- We managed to generate a abi file without namespace prefix  
- We have a getter defined in each system to get the systemId
Here the client needs to know which system the function lives in and gets the systemId and used the abi to generate the callData and sends to `callFrom(delegator, systemId, calldata)`

So the suggested approach of generating an ABI given a systemId might still present challenges in terms of client ease-of-use.

**Comment by holic** [comment]
closing this in favor of https://github.com/latticexyz/mud/issues/2491
