### ISSUE TITLE
consider emitting package version with store/world

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2372]
It would be useful to know the package version for store/world for debugging purposes

We could solve this by separately emitting the package version (which would increment more often than the current protocol version)

Or we can just get better at incrementing the protocol version (i.e. add CI tests to make sure this doesn't go stale when we change interfaces, events, etc.)

**Comment by yonadaaa** [comment]
I think we should address maintaining the protocol version first. For example, currently `WORLD_VERSION` is still `1.0.0-unaudited`, which is surely wrong because we've made multiple patches/minor changes?

If we aren't maintaining the protocol version, the package version will be even more annoying!

**Comment by holic** [comment]
We chatted and decided:
- update these version indicators to be called "protocol version"
- protocol version will be separate from package version (and increment slower)
- add CI action to detect changes in store/world source or ABIs to force you to increment the version if it changes
  - major = breaking change to interfaces
  - minor = backwards compatible additions to interfaces
  - patch = security patches of underlying implementation (no visible interface changes)
- separately maintain a list of audited protocol versions
