### ISSUE TITLE
Replace `EntityID`/ `EntityIndex` with native JavaScript `Symbol`

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#333]
Credit for this proposal goes to @holic 

### Current situation

- We're currently distinguishing between `EntityID` and `EntityIndex` on the client. `EntityID` is the entity's `uint256` value converted to a hex string, `EntityIndex` is a client only `number` referring to the entity's index in the client `World`'s `entities` array.
- The reason for this split is that we want to use entity ids as keys in our client components, but storing the raw hex string would cause a lot unnecessary memory usage (as the full id string would be duplicated in every component it is used as a key)
- However, this split frequently causes confusion and converting back and forth between index/id is inconvenient and requires access to the `World` object

### Proposal
- Use JavaScript's native [`Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) feature instead of a local mapping from id to index
- Symbols use a native global registry to map from number or string to symbol, and can be used to efficiently index objects/maps

**Usage**

```typescript
// ------- NEW -------
function entityToSymbol(entity: string) {
   return Symbol.for(entity);
}

function symbolToEntity(entitySymbol: symbol) {
   return Symbol.keyFor(entitySymbol);
}

// ------- OLD -------
function entityToIndex(entity: string, world: World) {
   return world.entityToIndex.get(entity);
}

function indexToEntity(entityIndex: number, world: World) {
   return world[entityIndex];
}
```
Note how this is a pure util and doesn't require access to the `world` object. We could go one step further and automate the conversion from entity to symbol and back within all MUD utils / components so devs never have to think about it.

<details>
<summary>Detailed symbol behavior</summary>

``` javascript
const a = Symbol("0x00")
// undefined

const b = Symbol("0x00")
// undefined

const c = Symbol.for("0x00")
// undefined

const d = Symbol.for("0x00")
// undefined

a == b
// false

a == c
// false

c == d
// true

Symbol.keyFor(a)
// undefined

Symbol.keyFor(c)
// '0x00'
```
</details>

**Comment by holic** [comment]
I wonder if it'd be worth stress testing this idea using OPCraft, since there's a lot of entities in there. We'd probably be able to quickly measure performance and memory requirements.

**Comment by 0xhank** [comment]
There are times when I want to define a client-only entity. At the moment they are incompatible with recs components so I am using five JS Maps to store them. For example: `const spriteRegistry = new Map<string | number, Phaser.GameObjects.Sprite>();`

This feels like an antipattern. I would like a way to define a native MUD recs component that can have any TS type and isn't indexed by `EntityIndex` -- instead it is indexed by a string.

This leads me to think EntityIndex should be a string instead of an abstracted number (I'm not sure if symbol would also be compatible with these requirements), and that the current system of using an enum of Solidity-friendly types is too inflexible for more complex applications. 

Tangentially related is that the custom component schema (defining a custom T) doesn't currently work when using Recs systems. Should this be a separate issue?
