### ISSUE TITLE
Discussion: using the table ID pre-image in the Metadata table as table name & requiring namespace as table name prefix

### ISSUE THREAD

**Issue by ludns** [latticexyz/mud#485]
Currently, when registering the metadata of a table, the table name has no connection with the table id, nor does it have to be unique.
This makes its use limited: it can't be used as a name downstream for MODE or in a frontend, as there is no guarantee on uniqueness. Even if it were to be unique, it would require syncing the Metadata table in order to use it as an alias for a table id.

I propose adding a check to the `setMetadata` function of `StoreCore` to keccak hash the table name and assert that it is the same as the table id.

This makes it such that table name and table id are interchangeable, and tools can recover the pre-image of table id and never have to display an "unknown" table id.

As a second proposal, I would like to motivate adding an extra requirement when Store is used with World.

World -- on top of the default API exposed by Store -- allows anyone on-chain to create a table. This will most probably lead to both name squatting and name sniping (where someone manages to include a TX registering a table with the same name / table id right before the registration TX is included).

I propose checking that that the table name starts with the namespace; partially mediating this issue. It could look like this (using JS syntax): `${namespace}_${tableName}` (purposefully not going with the `.` notation as it makes addressing a SQL table with a `.` require backticking);

Currently registering a table and setting its metadata happens over two different operations (and thus not atomic); which means someone could squat a table by providing the same table id, but without registering the metadata (which would fail here given they wouldn't have access to the namespace prefixing the table name). We could bundle these two operations on World, but I am also happy to discuss here.

**Comment by alvrs** [comment]
Since #467 we don't hash the table id with World and autogen anymore - the table id is just concat(`namespace`, `file`). On the one hand this makes it easier for MODE and other consumers to use a human readable table name, but on the other hand it prevents us from doing a `keccak(tableName) = tableId` check in Store's `setMetadata`. Since MODE should only depend on Store, not on World (to allow for use cases outside of World), we probably should not rely on the fact that table ids are always cleartext strings. What we can do in Store though is add a check for uniqueness of the table name, so the name can be used to map to the table id. (There could still be tables without a name because `setMetadata` is optional).

 On the World level we could require the `tableName` passed in `setMetadata` to correspond to something like `${namespace}_${tableName}` to make it consistent with the id.

**Comment by ludns** [comment]
Ok, so should MODE use the hexadecimal representation of the table id when no metadata is set, and then migrate to the table name in the Metadata table when available?
So you would query a table with its table id if there is no metadata, and with the table name if the metadata is available.

> On the World level we could require the tableName passed in setMetadata to correspond to something like `${namespace}_${tableName}` to make it consistent with the id.

Let's do it

**Comment by ludns** [comment]
tagging @authcall to get opinions on this from the MODE side

**Comment by holic** [comment]
we're now using a `bytes32` string that is a concat of `bytes16(namespace)` and `bytes16(name)` where both `namespace` and `name` are human readable
