### ISSUE TITLE
Consolidate JS build tooling

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#612]
We currently have a wide mix of these, and we should probably consolidate:
- ~~parcel, rollup, vite~~
- ~~tsup, tsc, esbuild~~
- ~~ts-node, tsx~~ #619 

If we're able to get rid of parcel in `network` package, we should remove `engines` from `package.json` (it's only there to fix parcel build issues).

**Comment by alvrs** [comment]
Context from discord: 

>Vite 
Pro - 1 tool that can build everything
Pro - Doubles as a test config don't need to configure babel or anything like with jest
Pro - Should have less hacky than otherwise ways of configuring dev builds to work with hot reloading
Con - Bit of overkill
>
>Tsup
Pro - Really fast even for prod build since it uses esbuild instead of rollup 
Pro - Really simple to configure
Pro - Definitely much simpler tool than vite
Con - You are forced to use different tool once you need to bundle an actual website or non typescript or struggle configuring it with tsup
>
>Tsc
Pro - It's typescript it's kinda the most obvious tool to use
Pro - Simplist to configure (sometimes)
Con - less forgiving than using esbuild
Con - slow
Con - boring
>
>Parcel
con - meh
>
>Rollup
Pro - most well documented build tool in js ecosystem
Pro - Plugin for everything
Pro - one build tool can do everything
Con - vite is basically a better version of rollup

Based on this I think we should try to consolidate to use `vite` everywhere

**Comment by holic** [comment]
vite -> tsup happened in https://github.com/latticexyz/mud/pull/660

just need to do parcel/rollup ones now!
