### ISSUE TITLE
Bug(mud2): calling systems from systems causes circular import issues

### ISSUE THREAD

**Issue by smallbraingames** [latticexyz/mud#677]
1. Say we have a system called `System` which wants to call another system. When you call a system from another system, you need to import the World interface `IWorld` (since system fns are called fron the world)
2. `IWorld` inherits `ISystem` however, since we also call `System` functions from the world.
3. `ISystem` imports things from `System`

Circular import!

**Comment by dk1a** [comment]
made a little example of circular systems
https://github.com/latticexyz/mud/compare/main...dk1a:mud:dk1a/example-temp
since `System` is kinda confusing I'll be referring to `IncrementSystem`, `IncrementWSystem` (W - Wrapper) and their interfaces

1. `IncrementSystem` doesn't implement `IIncrementSystem`, the interface is generated dynamically with `worldgen`. So when `IncrementSystem` imports `IWorld` and calls `IncrementWSystem` through it, there's not even a circular import (which would be fine anyways).
2. If `IncrementSystem` did implement `IIncrementSystem` (it's easy to do manually, though you normally wouldn't/shouldn't), it would still be fine, because both `IncrementSystem` and `IWorld` depend on `IIncrementSystem`, `IncrementSystem` doesn't depend on itself.
3. Even if `IncrementSystem` straight up called `IncrementWSystem` directly as a contract, and `IncrementWSystem` called `IncrementSystem` directly as well (as I do in that example, but that's obviously wrong in MUD), it would still kinda work (or at least compile), because while it is an infinite loop that uses MUD incorrectly, solidity allows contracts to import and/or call each other recursively.

For your 3rd point in particular - `ISystem` never imports things from `System`, since it's an interface. You could only really break things with circular inheritance, not just circular imports. Unless you do it with libraries, I'm not sure those can call each other as resiliently, since they have no interfaces.

**Comment by smallbraingames** [comment]
Yep–exactly, I should have clarified that, that's what I meant by "imports things from" it fails if there's like a struct etc. is used

**Comment by dk1a** [comment]
@smallbraingames try out the fix, see if it works for your systems
